### ISSUE TITLE
"cookieExp: 0" not working?

### ISSUE THREAD

**Issue by Sordum** [beeker1121/exit-intent-popup#1]
Hey,

when the option " cookieExp: 0" is on... the popup is shown everytime where it was included (but without black background).
Do you know why?

Many regards
Paul

**Comment by beeker1121** [comment]
Hi Paul,

setting cookieExp to 0 will make it so a cookie is never added to the page, thereby always showing the popup on every page view.  It should be showing the background as well - could you send me a link to the page you're seeing this problem on?

Regards,
Conner
