### ISSUE TITLE
Replace close icon

### ISSUE THREAD

**Issue by 2803media** [beeker1121/exit-intent-popup#10]
Hi do you know if it's possible to use <i class="fa fa-times-circle"></i> from fontawesome as a close icon? Thanks for your feedback

**Comment by mjraval** [comment]
Hi @2803media , 
    Well I am no Javascript or CSS expert , but you might want to look at [this line](https://github.com/beeker1121/exit-intent-popup/blob/master/js/bioep.js#L125) in the JS file. 

``` javascript
this.closeBtnEl.appendChild(document.createTextNode("X"));
```

Hope it helps.

**Comment by beeker1121** [comment]
I'm not familiar with fontawesome, but if for instance it's just using a custom `font-family`, you can include the font stylesheet in the header of your page, then add in the `font-family` declaration for `#bio_ep_close`.  The X for the close button is a regular text node.
