### ISSUE TITLE
Allow popping once per session

### ISSUE THREAD

**Issue by nimrod-cohen** [beeker1121/exit-intent-popup#13]
I believe that if you change the code to:
line 27: if(days && days > 0) { /\* added && days > 0 */

line 61: if(this.cookieExp < 0) { /\* replaced <= with < */

then setting cookieExp to 0 would mean once per session, while -1 would mean every time the page loads.

**Comment by beeker1121** [comment]
That's a good idea, and really that's probably how it should work so the user is only shown the popup once per browser session instead of on every page load when cookieExp is set to 0.  Let me take a look at your idea for the fix, I'll implement this soon.

**Comment by Soulfire86** [comment]
+1

**Comment by osworx** [comment]
If you add it, please only as option.
Because in situations (e.g. used in a webshop) this popup can be used as reminder that there are still products in the basket (if not already checked out).
If it would fix once per session but the user has just changed into another browser window (as I am doing often) and continue shopping the popup (as reminder) should work again.

**Comment by sirshurf** [comment]
Any news about this?

**Comment by beeker1121** [comment]
I apologize, I've been extremely busy working on another project and just haven't had the time to implement this and test. I'll have to look at this sometime in the near future, otherwise I'm open to PRs from anyone who wants to submit!

**Comment by beeker1121** [comment]
Implementing this today, and @osworx I'm going to make it an option, probably `showOncePerSession` which will be a `bool` set default to `false`. This should prevent any unexpected behavior in current implementations.

Just wanted to updated everyone, let me know if there's any issues!

**Comment by beeker1121** [comment]
Implemented in 4e8b0366c064e8bf58dc0e92a8fe13ba0b1a3d5c
