### ISSUE TITLE
Popup now triggering when mousing over the scrollbar

### ISSUE THREAD

**Issue by mattwschneider** [beeker1121/exit-intent-popup#14]
The latest updates have introduced a bug that triggers the popup when there is a mouseover of a scrollbar on the page.  I had to revert back to the version checked in on 11/21 in order to find a version working properly.

**Comment by beeker1121** [comment]
Fixing this now so it won't show when there's a mouseover on the scrollbar.  I may code better logic for it in the future.

**Comment by beeker1121** [comment]
Fix has been pushed to master.
