### ISSUE TITLE
 If the user navigates around on the website and e.g. leaves window on 3rd page, the cookie already exists and there is no popup

### ISSUE THREAD

**Issue by ysrinivasreddy** [beeker1121/exit-intent-popup#15]
I noticed that the cookie is always set, even if the mouse never leaves this window. As a result the popup only ever show while on the first page. If the user navigates around on the website and e.g. leaves window on 3rd page, the cookie already exists and there is no popup. How can I change this?

i don't want to put cookieExp option to 0, because it will fire on every page, i don't want to popup shows on every page load.
how can i solve this issue??

**Comment by StrangeWill** [comment]
Pull request #19 will only set the cookie if the exit intent window gets rendered.

**Comment by beeker1121** [comment]
Fixed by @StrangeWill
