### ISSUE TITLE
Please make this responsive on mobile screens. Thank you

### ISSUE THREAD

**Issue by clickdees** [beeker1121/exit-intent-popup#16]
I think your pop up is awesome. I would like to request that you make this responsive on mobile screens. Thank you

**Comment by zaplatynski** [comment]
It is very simple explained: on desktops you have a mouse and on mobile devices which are touch devices there is no mouse and the popup is controlled by a mouse event. However you can disable the exit intent event listening (the mouse movement event) and depend on the delay.
