### ISSUE TITLE
Hovering over a form field's "autocomplete" menu triggers popup

### ISSUE THREAD

**Issue by scottybo** [beeker1121/exit-intent-popup#20]
Issue: If someone is filling in a form and their browser shows previously filled entries and the user **hovers** over one of them, the popup triggers (as it thinks the person has left the browser window).

Problem seen in
- Firefox

Can't reproduce in
- Chrome
- Safari

**Comment by pdrazewski** [comment]
+1, same problem here

**Comment by adamfishercox** [comment]
Seen in chrome. Right clicking does the same, anything that takes you out of the context of the page itself.

**Comment by beeker1121** [comment]
I apologize, I've been extremely busy working on another project and just haven't had the time to implement a fix for this and test it fully. I'll have to look at this sometime in the near future, otherwise I'm open to PRs from anyone who wants to submit!

**Comment by beeker1121** [comment]
Will fix this today, just wanted to update everyone. Thanks!

**Comment by beeker1121** [comment]
Fixed in 4e8b0366c064e8bf58dc0e92a8fe13ba0b1a3d5c
