### ISSUE TITLE
Popup shown initial fix

### ISSUE THREAD

**Issue by mariokandut** [beeker1121/exit-intent-popup#23]
Hi,

the popup is shown, when the page is loaded. 

$(document).ready(function () {
bioEp.init(); }

To fix this I've added a class=hide to the div.

$(document).ready(function () {
var hidePopup = $(".hide");
bioEp.init(); 
hidePopup.removeClass("hide"); }

CSS: 
.hide {display:none;}

Just want to clarify if I've put the bioep.init(); in the wrong place or this is an improvement.

**Comment by beeker1121** [comment]
Hmm, if you're just calling `bioEp.init()`, then it should be using the default settings where the popup will show on exit intent after 5 seconds from page load. So with how you have it, it shouldn't be triggering automatically, it should only trigger when someone goes to leave the page.

Could you try to replicate this on jsfiddle or codepen (can edit the codepen from my blog post)? It will help determine the issue.

**Comment by beeker1121** [comment]
Feel free to reopen if you do discover this issue is persisting, otherwise I'm going to close it for now to keep the issue tracker at 0.
