### ISSUE TITLE
Add an option to close the popup when background is clicked

### ISSUE THREAD

**Issue by klein0r** [beeker1121/exit-intent-popup#25]
At the moment the popup will just close if the close button is used

**Comment by beeker1121** [comment]
I think this is a good idea, however I would prefer to have it be a custom solution for those that need it rather than bloat up the option count.

**Comment by alfonso100** [comment]
After line: 
`        this.addEvent(this.closeBtnEl, "click", function() {
            	bioEp.hidePopup()
        	});`

You can add: 

`this.addEvent(document.getElementById("bio_ep_bg"), "click", function() {
            	bioEp.hidePopup()
        	});`

and that will do the trick
