### ISSUE TITLE
Popup displays when the mouse move to scroll bar

### ISSUE THREAD

**Issue by sam24fs** [beeker1121/exit-intent-popup#26]
Popup displays when I move the mouse to scroll bar. This happens in Google Chrome. Do you have a fix for this issue?

**Comment by harrington101** [comment]
I'm seeing the same issue except it only happens when the user moves up and touches the scroll bar. If the user moves down and touches the scroll bar it works. Any solution?

**Comment by harrington101** [comment]
Hi Sam, you can edit the bioep.js file by changing the line just below the comment "This should be enough to signify exit intent" to this:
if(this.mouse.curY < this.mouse.lastY && (this.mouse.curY - window.scrollY) < 10) {

**Comment by beeker1121** [comment]
Will be merging a fix for this today!

**Comment by beeker1121** [comment]
Fixed with 7086924a157f933e4167ff37f6c5ec9b423c02bb

**Comment by sam24fs** [comment]
Perfect. Thank you!
