### ISSUE TITLE
Popup opens on load on mobile

### ISSUE THREAD

**Issue by atchavoshihnia** [beeker1121/exit-intent-popup#27]
I opened the page on an iPhone and was welcomed by the popup

**Comment by beeker1121** [comment]
Could you provide a live URL where this error happens?

**Comment by atchavoshihnia** [comment]
www.casamoda.com or www.venti.com

**Comment by beeker1121** [comment]
This is because you have the `showOnDelay` option set to `true`.

When this option is enabled, it will automatically display the popup after the given `delay` option time, which by default is 5 seconds.

To prevent it from showing up on delay, just set the `showOnDelay` option to `false`.
