### ISSUE TITLE
callback function would be awesome

### ISSUE THREAD

**Issue by itailulu** [beeker1121/exit-intent-popup#3]
a callback function would be awesome, for things like (Google Analytics) event tracking of the showPopup and hidePopup functions.

Great work!

**Comment by beeker1121** [comment]
Cool idea, I'll see about adding this in.  Thank you!

**Comment by sirshurf** [comment]
Any example about this?

**Comment by itailulu** [comment]
@sirshurf It's the standard way of using callbacks:

```
bioEp.init({
    width: 394,
    height: 298,
    html: '<a href="#YOURURLHERE" title="Claim your discount!"><img src="http://beeker.io/images/posts/2/template2.png" alt="Claim your discount!" /></a>',
    cookieExp: 0,
    onPopup: function() {
        alert("popped up!")
    }
});
```
@beeker1121 thnx for implementing this!
