### ISSUE TITLE
Trigger popup on different event

### ISSUE THREAD

**Issue by nocean** [beeker1121/exit-intent-popup#39]
Is there any way to trigger the popup using a different event (in addition to the exit intent)? For example, clicking a link would also trigger the popup?

**Comment by justinroodman** [comment]
yes.  this question was covered [here](http://beeker.io/exit-intent-popup-script-tutorial#comment15)

**Comment by nocean** [comment]
Thanks @justinroodman

**Comment by justinroodman** [comment]
@nocean no problem.  👍

**Comment by desmeit** [comment]
bioEp.showPopup(); is not working for me. I get the following error:

`Uncaught TypeError: Cannot read property 'showPopup' of undefined`

bioEp.init is working. What can I do?
