### ISSUE TITLE
Problems on newer Androids like Note 3?

### ISSUE THREAD

**Issue by ghost** [beeker1121/exit-intent-popup#5]
Being told that the popup is not resizing and that the "X" to close is not showing up at all...

**Comment by beeker1121** [comment]
Could be due to the missing vendor prefixes for positioning (which @spencerbrooks fixed).  I would try out the updated version of the popup with that merge.  If it's still happening, it's most likely due to conflicting CSS on the page (a global `div {}` declaration may affect the popup div(s))
