### ISSUE TITLE
Pop-Up not Scaling and Not in Center of the Page on iOS .

### ISSUE THREAD

**Issue by mjraval** [beeker1121/exit-intent-popup#6]
Hi,
   Thanks for this excellent script. The issue is on checking the script on iOS devices, (checked in iPhone 6 and 4S) , And the free simulator https://appetize.io/demo . The issue is I believe something do with the Transform Matrix but could not get any more idea. The pop-up is displayed at the bottom right of the page and displays only the top left part of the popup. I have attached a screen shot of this taken from the Appetize.io simulator. 
![2015-08-06 09-20-17 screenshot](https://cloud.githubusercontent.com/assets/5053486/9107151/02f629fc-3c1d-11e5-8a44-20bcf0cbe5a1.jpg)

Thanks

**Comment by spencerbrooks** [comment]
You can grab the [fixed version in my fork](https://github.com/spencerbrooks/exit-intent-popup) while waiting for the changes to be merged, if you want.

**Comment by mjraval** [comment]
Thanks for the Fix, @spencerbrooks much appreciated. It does bring the pop-up to the Center now. These is a little issue I am facing though, it is not showing the close button on the top right, essentially stripping off the about 20-25 pixels on each side. Can you please suggest something for this.

![2015-09-24 09-51-26 screenshot](https://cloud.githubusercontent.com/assets/5053486/10069131/ebc6c9d4-62a1-11e5-9ba2-7de7ef58cf8b.jpg)
I believe it's some thing to do with the scalePopup at [this function](https://github.com/beeker1121/exit-intent-popup/blob/master/js/bioep.js#L155-L195), but thats pretty much all I could figure out. 

``` javascript
scalePopup: function() {
        var margins = { width: 40, height: 40 };
        var popupSize = { width: bioEp.popupEl.offsetWidth, height: bioEp.popupEl.offsetHeight };
        var windowSize = { width: window.innerWidth, height: window.innerHeight };
        var newSize = { width: 0, height: 0 };
        var aspectRatio = popupSize.width / popupSize.height;

        // First go by width, if the popup is larger than the window, scale it
        if(popupSize.width > (windowSize.width - margins.width)) {
            newSize.width = windowSize.width - margins.width;
            newSize.height = newSize.width / aspectRatio;

            // If the height is still too big, scale again
            if(newSize.height > (windowSize.height - margins.height)) {
                newSize.height = windowSize.height - margins.height;
                newSize.width = newSize.height * aspectRatio;
            }
        }

        // If width is fine, check for height
        if(newSize.height === 0) {
            if(popupSize.height > (windowSize.height - margins.height)) {
                newSize.height = windowSize.height - margins.height;
                newSize.width = newSize.height * aspectRatio;
            }
        }

        // Set the scale amount
        var scaleTo = newSize.width / popupSize.width;

        // If the scale ratio is 0 or is going to enlarge (over 1) set it to 1
        if(scaleTo <= 0 || scaleTo > 1) scaleTo = 1;

        // Save current transform style
        if(this.transformDefault === "") 
            this.transformDefault = window.getComputedStyle(this.popupEl, null).getPropertyValue("transform");

        // Apply the scale transformation
        this.popupEl.style.transform = this.transformDefault + " scale(" + scaleTo + ")";
    }
```

Many Thanks

**Comment by spencerbrooks** [comment]
I suspect this is probably an issue with your custom CSS rather than the JS library, though I'm not positive without being able to see it in action.

I would first try to remove most (or all) of your custom CSS, specifically fixed width declarations, to see if the problem goes away. If so, you can use media queries and play with your styles until you get it working correctly on iOS/mobile.

If you are still having this problem with no customizations, it would help to be able to see the behavior in action (e.g. on a development server somewhere).

**Comment by mjraval** [comment]
Hi @spencerbrooks  , 
    Thanks alot for taking your time to reply.  As per your recommendation I have removed all of the CSS and just left content of the pop-up but it is still having the same issue. Just to mention again, it works on Android with Chrome but not Default Browser of Android and not in iOS both safari and Chrome [This is the dev Link](http://goo.gl/OE536v) . My Init function is below

``` javascript
bioEp.init({
    width: 550,
    height: 450,
    html: '<div id="bio_ep_content">' +
    '<span class="one">Head Text <br/></span>' +
    '<span class="two">Sub Heading Text<br/> Another Piece of Text</span>' +

    '<span class="address-header">Information</span>' +
    '<a class="address">point 1. <br> Point 2 <br> Point 3</a>' +
    '</div>',
    css: '#bio_ep {color: #fff; background-color: rgba(0,0,0,0.8); text-align: center;}' +
    '#bio_ep_content {padding: 15px 15px 15px 25px; font-family: "Lato";}' +
    '.one {display: block; color: #f44d3c; font-size: 32px; font-weight: 600;}' +
    '.two {display: block; font-size: 16px;}' +
    '.three {display: block; margin: -5px 0 0 0; font-size: 16px;}' +
    '.address {display: inline-block; margin: 10px 0 0 0; font-family: "Bitter"; padding: 7px;; color: #fff; font-size: 44px; background-color: #f44d3c; -webkit-appearance: none; -moz-appearance: none; border-radius: 0; text-decoration: none;}' +
    '.address-header {display: block; font-family: "Lato" !important ; padding-top: 10px; font-size: 37px;}',
    cookieExp: 0,
    showOnDelay: true,
    delay: 2,
    fonts: ['@import url(http://fonts.googleapis.com/css?family=Bitter:400);','@import url(http://fonts.googleapis.com/css?family=Lato:300,400);']
});
```

I would really appreciate it , if you can give me some pointer on this. 

Many Thanks

**Comment by spencerbrooks** [comment]
@onlyyou2323: I checked your development link on Chrome's iOS device simulator (in dev tools), plus an actual iPhone 5S, and am not able to reproduce the issue. The full popup, including the close button, is visible for me on both - nothing is cut off.

Is there anything I'm missing?

**Comment by mjraval** [comment]
@spencerbrooks : Thanks for taking a look on this, I was just testing on a Colleague's iPhone 6, and it seems the issue is just with iPhone 4 and 6 ,  as on checking it on a friend's iPhone 5 (android user here) seems to be working fine.  And most simulators do not seem to catch this issue, but actual device having showing the issue. 
- iPhone 4 : Not working
- iPhone 5 : Working
- iPhone 6 : Not Working
  *iPad : Not Working () 

I am in some sort of deep mess here. to be honest for the moment , I have disabled this for iOS devices but would be good to figure out the the actual cause for this.

Many Thanks

**Comment by spencerbrooks** [comment]
@onlyyou2323: I was able to reproduce the issue you were talking about using the iOS Simulator on XCode.

Please remove the width and height declarations from `bioEp.init()`:

```
width: 550,
height: 450
```

This causes the popup to be set to a fixed width on small devices such as the iPhone 4, which is only 320px wide.

Personally, I would recommend you declare at least your CSS outside the `init()` function so you can use media queries to target devices. Something to this effect:

```
 #bio_ep {
     width: 550px;
     height: 450px;
     ...
  }

  @media only screen and (max-width: 449px) {
      #bio_ep {
          width: 90%;
          height: 90%;
          ...
      }
  }
```

Hope that helps!

**Comment by mjraval** [comment]
@spencerbrooks , you are a star mate. This one fixed it all for me. Really appreciate your time and help. Many Thanks.

**Comment by beeker1121** [comment]
I apologize for taking so long to merge everything - glad you got it working now @onlyyou2323 , and thank you @spencerbrooks !
